# Generated by Django 3.2.9 on 2021-11-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICC_Tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearer',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
