# Generated by Django 3.2.9 on 2021-11-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICC_Tracking', '0002_alter_bearer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[(1, 'Preparing'), (2, 'Active'), (3, 'Delivered')], default=1, max_length=30),
        ),
    ]
