# Generated by Django 3.2.9 on 2021-11-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICC_Tracking', '0003_alter_order_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearer',
            name='assignedOrders',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bearer',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contactEmail',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contactNumber',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='orderID',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='assignedBearer',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.FloatField(blank=True, max_length=30),
        ),
    ]
