# Generated by Django 3.2.9 on 2021-11-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICC_Tracking', '0004_auto_20211124_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.IntegerField(choices=[(1, 'Preparing'), (2, 'Active'), (3, 'Delivered')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.FloatField(blank=True),
        ),
    ]
