# Generated by Django 3.2.9 on 2021-11-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICC_Tracking', '0005_auto_20211124_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='customer',
            name='assignedBearer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='orderStatus',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Delivered')], default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='subtotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='orderID',
            field=models.CharField(max_length=50),
        ),
    ]
