# Generated by Django 3.2.9 on 2021-11-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICC_Tracking', '0007_bearer_bearerstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orderID',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
