# Generated by Django 3.2.9 on 2021-11-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICC_Tracking', '0008_alter_customer_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearer',
            name='bearerStatus',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='orderStatus',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
    ]
