# Generated by Django 3.2.9 on 2021-11-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICC_Tracking', '0009_auto_20211126_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.IntegerField(choices=[(1, 'PortmorePines'), (2, 'Caribbean Estate'), (3, 'Monza Daytona'), (4, 'Portmore Country Club1'), (5, 'Braeton'), (6, 'Bridgeport'), (7, 'Bridgeview'), (8, 'Edgewater'), (9, 'Greater Portmore'), (10, 'Gregory Park'), (11, 'Independence City, Cedar Grove, Cumberland, Christian Gardens'), (12, 'Naggo Head'), (13, 'Newland,South Borough'), (14, 'Passage Fort, Weschester, Westmeade, Garveymeade'), (15, 'Port Henderson'), (16, 'Portmore Country Club 2'), (17, 'Waterford'), (18, 'Waterford Boston'), (19, 'Waterford Gaza'), (20, 'Waterford Saltpond'), (21, 'Caymanas Golf & Country Club'), (22, 'Phoenix Park Village'), (23, 'Hellshire')], default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='time',
            field=models.IntegerField(choices=[(1, '180'), (2, '360'), (3, '300'), (4, '300'), (5, '600'), (6, '360'), (7, '480'), (8, '480'), (9, '480'), (10, '960'), (11, '780'), (12, '300'), (13, '300'), (14, '600'), (15, '300'), (16, '180'), (17, '900'), (18, '900'), (19, '900'), (20, '900'), (21, '1080'), (22, '600'), (23, '2340')], default=1),
        ),
    ]
