# Generated by Django 3.2.9 on 2021-11-28 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ICC_Tracking', '0010_auto_20211127_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='timeCreated',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
