# Generated by Django 3.2.9 on 2021-11-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICC_Tracking', '0011_customer_timecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='Test Address 11', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fname',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lname',
            field=models.CharField(default='Name', max_length=50),
        ),
    ]
